using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using VetCareBackend.Application.dtos.Requests;
using VetCareBackend.Application.dtos.Responses;
using VetCareBackend.Application.Interfaces;
using VetCareBackend.Infrastructure.ExternalService;

namespace VetCareBackend.Presentation.Controllers
{
    [Route("api/auth")]
    [ApiController]
    public class AuthController : ControllerBase
    {
        private readonly IAuthService _service;
        private readonly IConfiguration _configuration;
        public AuthController(IAuthService service, IConfiguration configuration)
        {
            _service = service;
            _configuration = configuration;
        }
        /// <summary>
        /// This endpoint allows a new user to sign up by providing their details. 
        /// It accepts a SignUpRequest object in the request body and returns an AuthResponse object upon successful registration.
        /// </summary>
        [HttpPost("signup")]
        [AllowAnonymous]
        public async Task<ActionResult<AuthResponse>> SignUp([FromBody] SignUpRequest request)
        {
            var response = await _service.SignUp(request);
            SetAccessTokenCookie(response.Token);
            response.Token = string.Empty;
            return StatusCode(StatusCodes.Status201Created, response);
        }
        /// <summary>
        /// This endpoint allows an existing user to sign in by providing their credentials.
        /// If the user has two-factor authentication enabled, no session cookie is issued yet:
        /// a short-lived pending token is returned and must be exchanged via /2fa/verify.
        /// Otherwise, the issued JWT is set as an httpOnly cookie and is not included in the response body.
        /// </summary>
        [HttpPost("signin")]
        [AllowAnonymous]
        public async Task<ActionResult<AuthResponse>> SignIn([FromBody] SignInRequest request)
        {
            var response = await _service.SignIn(request);

            if (response.TwoFactorRequired)
            {
                return Ok(response);
            }

            SetAccessTokenCookie(response.Token);
            response.Token = string.Empty;
            return Ok(response);
        }
        /// <summary>
        /// Starts two-factor authentication enrollment for the current user, generating a new TOTP secret.
        /// Returns an otpauth:// URI to be rendered as a QR code. The secret is not activated until confirmed.
        /// </summary>
        [HttpPost("2fa/enable")]
        [Authorize]
        public async Task<ActionResult<TwoFactorSetupResponse>> EnableTwoFactor()
        {
            var userId = GetCurrentUserId();
            var response = await _service.BeginTwoFactorEnrollment(userId);
            return Ok(response);
        }
        /// <summary>
        /// Confirms two-factor enrollment with the first TOTP code generated by the authenticator app.
        /// On success, two-factor authentication is activated.
        /// </summary>
        [HttpPost("2fa/confirm")]
        [Authorize]
        public async Task<ActionResult> ConfirmTwoFactor([FromBody] TwoFactorConfirmRequest request)
        {
            var userId = GetCurrentUserId();
            await _service.ConfirmTwoFactorEnrollment(userId, request.Code);
            return Ok();
        }
        /// <summary>
        /// Second step of sign-in for users with two-factor authentication enabled.
        /// Exchanges the pending token and a TOTP (or recovery) code for a full session cookie.
        /// </summary>
        [HttpPost("2fa/verify")]
        [AllowAnonymous]
        public async Task<ActionResult<AuthResponse>> VerifyTwoFactor([FromBody] TwoFactorVerifyRequest request)
        {
            var response = await _service.VerifyTwoFactor(request.PendingToken, request.Code);
            SetAccessTokenCookie(response.Token);
            response.Token = string.Empty;
            return Ok(response);
        }
        /// <summary>
        /// Disables two-factor authentication for the current user. Requires re-entering the password.
        /// </summary>
        [HttpPost("2fa/disable")]
        [Authorize]
        public async Task<ActionResult> DisableTwoFactor([FromBody] TwoFactorDisableRequest request)
        {
            var userId = GetCurrentUserId();
            await _service.DisableTwoFactor(userId, request.Password);
            return Ok();
        }
        private Guid GetCurrentUserId()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier) ?? User.FindFirstValue("sub");
            return Guid.Parse(userId!);
        }
        /// <summary>
        /// This endpoint logs the user out by clearing the access token cookie.
        /// </summary>
        [HttpPost("signout")]
        [AllowAnonymous]
        public new ActionResult SignOut()
        {
            Response.Cookies.Delete("access_token", new CookieOptions
            {
                HttpOnly = true,
                Secure = true,
                SameSite = SameSiteMode.None
            });
            return Ok();
        }
        /// <summary>
        /// This endpoint returns the currently authenticated user's basic info, resolved from the access token cookie.
        /// Used by the frontend to restore session state on page load.
        /// </summary>
        [HttpGet("me")]
        [Authorize]
        public async Task<ActionResult<AuthResponse>> Me()
        {
            var email = User.FindFirstValue(ClaimTypes.Email);
            var role = User.FindFirstValue(ClaimTypes.Role);
            var userId = GetCurrentUserId();

            return Ok(new AuthResponse
            {
                UserId = userId,
                Email = email ?? string.Empty,
                Role = role ?? string.Empty,
                TwoFactorEnabled = await _service.IsTwoFactorEnabled(userId)
            });
        }

        private void SetAccessTokenCookie(string token)
        {
            int expirationMinutes = int.Parse(_configuration["Jwt:ExpirationMinutes"]!);

            Response.Cookies.Append("access_token", token, new CookieOptions
            {
                HttpOnly = true,
                Secure = true,
                SameSite = SameSiteMode.None,
                Expires = DateTimeOffset.UtcNow.AddMinutes(expirationMinutes)
            });
        }
        /// <summary>
        /// This endpoint allows users to request a password reset.
        /// It receives the registered email address and, if it exists in the system, sends an email with a reset link.
        /// For security reasons, it always returns the same message without confirming whether the email address exists or not.
        /// </summary>
        [HttpPost("forgost-post")]
        [AllowAnonymous]
        public async Task<ActionResult> ForgotPassword([FromBody] ForgotPasswordRequest request)
        {
            await _service.ForgotPassword(request);
            return Ok(new { message = "Si el mail existe, recibiras las instrucciones" });
        }
        /// <summary>
        /// This endpoint allows the user to reset their password.
        /// It accepts the token sent via email and the desired new password.
        /// The token must be valid, must not have been used previously, and must not have expired.
        /// </summary>
        [HttpPost("reset-password")]
        [AllowAnonymous]
        public async Task<ActionResult> ResetPassword([FromBody] ResetPasswordRequest request) 
        {
            await _service.ResetPassword(request);
            return Ok(new { message = "Contraseña actualizada correctamente" });
        }
    }
}
